### ISSUE TITLE
How to set event on position of an Object

### ISSUE THREAD

**Issue by AmirDoreh** [splinetool/react-spline#153]
The ultimate goal is to change the scene according to the position of one single specific object so we need to have a event listener on position of the object  , we went through documentation but did not get a clear picture of the right implementation.

**Comment by AdrianFahrbach** [comment]
Were you able to solve this?
I'm currently polling the positions of my objects every x seconds, but it seems like they only update when being dragged (at least for objects with a drag event and dynamic physics).

**Comment by superguigui** [comment]
I think what you want to do is look at the distance event inside of Spline editor.
This way you can just set up invisible target objects that trigger various actions when objects get close enough to them (this is configurable).
Feel free to join the official community Discord if you need some help. https://discord.gg/M9hNDMqvnw

**Comment by AdrianFahrbach** [comment]
> I think what you want to do is look at the distance event inside of Spline editor.

That was my workaround, but this approach has a lot of limitations.
In one of my cases I have multiple letters that can be dragged around to form words. I would like to check for completed words through the API (no feasible way to do this inside Spline), but I can't.
I think it would generally be nice if we could access the actual position of a dynamic object through the API.

**Comment by superguigui** [comment]
> I think it would generally be nice if we could access the actual position of a dynamic object through the API.

It's possible through the [runtime API](https://www.npmjs.com/package/@splinetool/runtime), which is exposed by react-spline through the onLoad event. It's imperative though so you need a bit of gymnastic to use it from react but it should work. Here's an example: https://codesandbox.io/p/devbox/untitled-forked-kxhv48?file=%2Fsrc%2FApp.jsx%3A12%2C53

**Comment by AdrianFahrbach** [comment]
> It's possible through the [runtime API](https://www.npmjs.com/package/@splinetool/runtime), which is exposed by react-spline through the onLoad event. It's imperative though so you need a bit of gymnastic to use it from react but it should work. Here's an example: https://codesandbox.io/p/devbox/untitled-forked-kxhv48?file=%2Fsrc%2FApp.jsx%3A12%2C53

This doesn't work for objects with dynamic physics though. My draggable letters always return the last position where they have been dragged, not the position where they are actually at.

I adjusted your example to show this: https://codesandbox.io/p/devbox/untitled-forked-9grl47
Try "throwing" the sphere and you will see that the x coordinate doesn't update anymore once you let go. In addition to that you can also move the cube by pushing it with the sphere, because then the cubes x coordinate won't update.

**Comment by superguigui** [comment]
Right... Physics is a bit particular because it's applied directly to the world matrix of the object for performance reasons and we can't override the current proxy with it without breaking the set functionality of said proxy. For read purpose we can look at exposing the world matrix of the object though. We will consider this!
