### ISSUE TITLE
Lighthouse performance issues | ‌Finding Best Practices

### ISSUE THREAD

**Issue by mostafa-rio** [splinetool/react-spline#168]
What are the best practices to avoid performance issue when using spline tool in react
Just by defining an instance of Spline you can see drastic performance drops in lighthouse tests.

Performance of react app before adding Spline:
<img width="511" alt="Screenshot 2023-12-24 at 11 44 09" src="https://github.com/splinetool/react-spline/assets/32630862/687546b3-f56c-4939-8aa3-1af3ae39a41e">

Performance after implementing Spline:
<img width="505" alt="Screenshot 2023-12-24 at 13 08 21" src="https://github.com/splinetool/react-spline/assets/32630862/06c2afec-ed50-44d5-80f5-e74b9028c403">

**Comment by Tenkir** [comment]
Do you have the details as to why lighthouse is dropping the performance score?

**Comment by mostafa-rio** [comment]
One of the main reasons is the high execution time for spline js scripts. For example in my case lighthouse is mentioning that /assets/react-spline.js execution time needs to be reduced and it's directly effecting the total blocking time or TBT.

**Comment by att1106** [comment]
do you have any suggestions how to improve the performance score. i only came up with lazy loading...

**Comment by superguigui** [comment]
Lazy loading is a good idea indeed!

Our latest RSC compatible export for next.js (see Next.js code export in the editor) also helps a bit because we make it first display a blurry preview of the scene server side which we replace client-side by the actual canvas.

But lighthouse in general does not play well with interactive 3d content because it was built to measure usage of simpler scripts and static content like images, text, or even videos. But in order to display a Spline scene (or even a WebGL scene in general) which is highly interactive and goes way beyond static content, we need to embed a whole engine in order to display and interact with those. This comes with a price of needing to load the both the script of the engine and the data and asset of the scene, which Lighthouse flags as unnecessary big (and it's not that big in modern web, most animated gifs are bigger for an example).

And this is just the loading part, then you have to account for performance itself which is driven by your scene and what it contains. The bigger / more complex the scene the harder it will be to render it for the browser, so any optimization you can do from the editor will help (ex: reduce number of textures and their size, reuse materials, don't subdivide geometries too much etc...).

All in all it's a world of tradeoff, first ask yourself if it's not better to export the spline scene as an image or video, but if you need interactivity then this is more or less the price to pay.

That being said we are constantly working toward making the runtime smaller and more modular so keep your eyes open !
