### ISSUE TITLE
EmitEvent not working React

### ISSUE THREAD

**Issue by PedroDiasVeloso** [splinetool/react-spline#172]
I have a scene with zIndex 0 and a div with zIndex 1 on top, this makes it impossible to click on the scene objects to trigger mouse down events,I created a button and tried to emit the event both using spline.emitEvent("mouseDown", "Sphere") and sphere.emitEvent("mouseDown"),
none of them does anything, is there anything else that needs do be done  for them to work ?

**Comment by sebbooth** [comment]
Could be that you're calling emitEvent on just `spline` instead of `spline.current`. You can see how they use `useRef` and `onLoad` in this example from the readme.

```jsx
import { useRef } from 'react';
import Spline from '@splinetool/react-spline';

export default function App() {
  const spline = useRef();

  function onLoad(splineApp) {
    // save the app in a ref for later use
    spline.current = splineApp;
  }

  function triggerAnimation() {
    spline.current.emitEvent('mouseHover', 'Cube');
  }

  return (
    <div>
      <Spline
        scene="https://prod.spline.design/6Wq1Q7YGyM-iab9i/scene.splinecode"
        onLoad={onLoad}
      />
      <button type="button" onClick={triggerAnimation}>
        Trigger Spline Animation
      </button>
    </div>
  );
}
```

You can also try using the "Development Object ID", which you can get by right-clicking on the object in the spline editor. It will look something like:
```jsx
spline.current.emitEvent("mouseDown", "a9538c57-e316-48df-b44b-e45e091d993b")
```
