### ISSUE TITLE
Plans to add Create Object Action

### ISSUE THREAD

**Issue by randyfinfare** [splinetool/react-spline#194]
Is there currently a way or any plans to add the ability to create objects dynamically?

**Comment by superguigui** [comment]
@randyfinfare there is a Create Object Action in Spline.
<img width="558" alt="image" src="https://github.com/splinetool/react-spline/assets/400119/6b7bb7db-3b7f-4e11-92bd-920a1fb38821">

I'm closing this but you can create a new Discussions instead of an issue if you want precision. I suggest going to the Spline discord server for feature request or help 👍
