### ISSUE TITLE
I can't adjust the height of the React Spline Element

### ISSUE THREAD

**Issue by akpamaboris** [splinetool/react-spline#26]
Hi how are you ?

I can not adjust the height of the React Spline element. If i put style on it, it does nothing.
Is it normal ?

Best Regards

![image](https://user-images.githubusercontent.com/33418718/160863410-f58d63c1-5a81-411f-8834-e0b709e2e85a.png)

**Comment by alanwong9179** [comment]
> 

Hi akpamaboris, here is my solution, although i think it isn't the best way to do so.
Please make sure your animation is loaded before run the adjustment code
Also, make sure you are controlling the height and width after you mouse event triggered you 3D model
 
![Screenshot 2022-03-31 at 11 08 32 PM](https://user-images.githubusercontent.com/33627904/161088351-11921ad0-ca71-420e-9109-7d81cb34cfdf.png)
![Screenshot 2022-03-31 at 11 09 15 PM](https://user-images.githubusercontent.com/33627904/161088524-65dde4ce-69f1-43b7-9ded-57d502355634.png)

**Comment by akpamaboris** [comment]
Thank you for your reply, interesting. Have a great day

**Comment by michaeljblum** [comment]
Really tool tool but it would help exposing a bit more robust access to things like canvas width and height and camera. I can't seem to access camera in order to refocus the object in the scene upon resizing canvas as recommended above. Also, the canvas size reverts to full viewport width/height as soon as the viewport is slightly resized. 

I'll try and look into this too. Thanks again.

**Comment by Walidoux** [comment]
@michaeljblum Got the same problem, because of that I can't keep up with my project and my feature is currently scheduled until it's fixed because, as you said:

> the canvas size reverts to full viewport width/height as soon as the viewport is slightly resized.

Here's what it actually renders:

https://user-images.githubusercontent.com/87608619/162589442-51b98449-2078-4173-874a-f371b11c09a0.mov
